name: Build and Test Script

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get remove -y containerd containerd.io
        sudo apt-get install -y docker-ce docker-ce-cli